services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      # - node_modules:/frontend/node_modules
      # - /app/node_modules 
    environment:
      - HOST=0.0.0.0

  # auth-service:
  #   build: ./services/AuthService
  #   ports:
  #     - "5001:5000"
  #   env_file:
  #     - ./services/AuthService/.env
  #   depends_on:
  #     - auth-db

  # auth-db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: authuser
  #     POSTGRES_PASSWORD: authpass
  #     POSTGRES_DB: authdb
  #   ports:
  #     - "5433:5432"
  #   # volumes:
  #   #   - auth-db-data:/var/lib/postgresql/data

  # product-service:
  #   build: ./services/ProductService
  #   ports:
  #     - "5002:5000"
  #   env_file:
  #     - ./services/ProductService/.env
  #   depends_on:
  #     - product-db

  # product-db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: productuser
  #     POSTGRES_PASSWORD: productpass
  #     POSTGRES_DB: productdb
  #   ports:
  #     - "5434:5432"
    # volumes:
    #   - product-db-data:/var/lib/postgresql/data
